### PR TITLE
add OP_CSV

### PR DESCRIPTION
**Pull request by dcousens**
First things first

### CODE REVIEW

**Comment by mandelmonkey** [comment]
Will this be added? I can use OP_NOP3 but would be nice to write OP_CHECKSEQUENCEVERIFY or OP_CSV in the code instead

**Comment by dcousens** [comment]
Waiting for any @bitcoinjs/committers to approve/ACK the PR :S

**Review by dabura667 — APPROVED** [review]
LGTM

**Comment by dcousens** [comment]
published as `v1.4.0`

**Pull request merged**
